### ISSUE TITLE
Method mistake for getDirectivesFor() in README

### ISSUE THREAD

**Issue by halfer** [webignition/robots-txt-file#3]
The code examples refer to a method called `getDirectivesForUserAgent()` - this should be `getDirectivesFor()`. I guess this must have changed in the code?

**Comment by webignition** [comment]
Yes, I guess so. I'll sort that out before too long. Thanks for spotting it!

**Comment by webignition** [comment]
Fix in 60af3f5708e58fe05bce2f710f1210e665f5c33c

**Comment by halfer** [comment]
Thanks for the fix! :)
