### ISSUE TITLE
Feature request: isAllowed()

### ISSUE THREAD

**Issue by greendrake** [webignition/robots-txt-file#5]
I am building a considerate bot which does not really care about directives and sitemaps. All it needs to know is whether or not it is allowed to access a certain path. Is it possible to use this software in that fashion already? For example, something like:

``` php
$parser = new \webignition\RobotsTxt\File\Parser();
$parser->setContent(file_get_contents('http://example.com/robots.txt'));
$parser->setUserAgent('MyBot');
var_dump($parser->isAllowed('/foo'));
```

**Comment by hbea2014** [comment]
+1 
Same here :)

**Comment by LeMoussel** [comment]
:+1:

**Comment by webignition** [comment]
@greendrake That's a great idea, I'd certainly like to implement that soon.

**Comment by webignition** [comment]
This is now present in the [2.0 release](https://github.com/webignition/robots-txt-file/releases/tag/2.0)

See example at https://github.com/webignition/robots-txt-file/blob/master/README.md#check-if-a-user-agent-is-allowed-to-access-a-url-path
