### ISSUE TITLE
Install with composer fail

### ISSUE THREAD

**Issue by LeMoussel** [webignition/robots-txt-file#7]
Like describe in ReadMe, I update composer.json like this 

> ```
> "require": {
>   "php": ">=5.3.0",
>   "webignition/robots-txt-file": "dev-master",        
>   "webignition/robots-txt-parser": "dev-master",
>   "webignition/disallowed-character-terminated-string": ">=1.0"       
> }
> ```

But when I run `composer update` I receive the following error :

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for webignition/robots-txt-parser dev-master -> satisfiable by webignition/robots-txt-parser[dev-master].
    - webignition/robots-txt-parser dev-master requires webignition/robots-txt-file >=0.1,<1.0 -> satisfiable by webignition/robots-txt-file[0.1, 0.2] but these conflict with your requirements or minimum-stability.
```

**Comment by LeMoussel** [comment]
Seems to be OK with this configuration

> "require": {
>   "php": ">=5.3.0",
>   "webignition/robots-txt-file": "*",        
>   "webignition/robots-txt-parser": "*",
>   "webignition/disallowed-character-terminated-string": "*"       
> }

**Comment by webignition** [comment]
@LeMoussel Thanks for pointing this out, fixing in https://github.com/webignition/robots-txt-file/pull/11
