### ISSUE TITLE
Not Valid directive mistake

### ISSUE THREAD

**Issue by LeMoussel** [webignition/robots-txt-file#8]
with this robots.txt content 
```
User-agent: *
Disallow:
```
And this code, I got not valid directive for "Disallow".  I think this is an error because this directive is correct.
**Rem:** this sites indicates that is valid robots.txt file with no Warning or Fail error.
[ SeoBook Robots.txt Analyser](http://tools.seobook.com/robots-txt/analyzer/)
[SeoSiteCheckup Robots.txt](http://seositecheckup.com/seo-audit/robotstxt-test/f4b1.com/robots.txt) 
```
$parser = new \webignition\RobotsTxt\File\Parser();
$parser->setContent(file_get_contents('http://f4b1.com/robots.txt'));
$robotsTxtFile = $parser->getFile();
foreach($robotsTxtFile->GetAllDirectives() as list($field, $value, $valid)) {
            if ($valid === FALSE) { echo "Invalid directive $field => $value"; }
}
```

**Comment by webignition** [comment]
@LeMoussel Thanks for pointing this out.

What you say sounds right (that this is a bug). I'll quickly review the robots txt spec just to be sure and then I'll look into a fix.

**Comment by webignition** [comment]
Yep, according to [the spec](http://www.robotstxt.org/orig.html):

> Any empty value, indicates that all URLs can be retrieved. At least one Disallow field needs to be present in a record.

**Comment by webignition** [comment]
Fixed in https://github.com/webignition/robots-txt-file/releases/tag/0.3
